# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{active_model_message_translation}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sven Fuchs", "Mateo Murphy"]
  s.date = %q{2010-02-13}
  s.extra_rdoc_files = [
    "README.textile",
     "TODO"
  ]
  s.files = [
    "README.textile",
     "TODO",
     "VERSION",
     "lib/active_model/error.rb",
     "lib/active_model/errors_ext.rb",
     "lib/core_ext/error_comparsion.rb",
     "lib/i18n/message.rb",
     "lib/i18n/message/base.rb",
     "lib/i18n/message/cascade.rb",
     "lib/i18n/message/format.rb",
     "lib/i18n/message/formatted.rb",
     "lib/i18n/message/gettext.rb",
     "lib/i18n/message/variants.rb",
     "test/active_model/run_tests.rb",
     "test/active_model_test.rb",
     "test/all.rb",
     "test/behavior.rb",
     "test/behavior/base.rb",
     "test/behavior/cascade.rb",
     "test/behavior/formatted.rb",
     "test/behavior/gettext.rb",
     "test/behavior/other.rb",
     "test/behavior/variants.rb",
     "test/message/all_features_test.rb",
     "test/message/base_test.rb",
     "test/message/cascade_test.rb",
     "test/message/formatted_test.rb",
     "test/message/gettext_test.rb",
     "test/message/variants_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/svenfuchs/active_model_message_translation}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Proposal for validation error messages in ActiveModel}
  s.test_files = [
    "test/active_model/run_tests.rb",
     "test/active_model_test.rb",
     "test/all.rb",
     "test/behavior/base.rb",
     "test/behavior/cascade.rb",
     "test/behavior/formatted.rb",
     "test/behavior/gettext.rb",
     "test/behavior/other.rb",
     "test/behavior/variants.rb",
     "test/behavior.rb",
     "test/message/all_features_test.rb",
     "test/message/base_test.rb",
     "test/message/cascade_test.rb",
     "test/message/formatted_test.rb",
     "test/message/gettext_test.rb",
     "test/message/variants_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

